; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

; 시리얼 출력을 파일로 저장한다.
; log2file  : 프로젝트 폴더에 로그 파일을 만든다
; send_on_enter : 모니터에서 입력한 내용을 Enter 로 보드에 전송한다 (구간 마커용)
monitor_filters = log2file, send_on_enter
